app:
  name: config-server
  eureka:
    default:
      zone: http://localhost:8761/eureka/
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans
  kafka:
    bootstrap:
      servers: localhost:9092
    max:
      poll:
        interval:
          ms: 60000
        records: 10    
